name: Build FB Group Exporter

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Используем v2 для совместимости с runner 2.324.0
    
    - name: Set up Python
      uses: actions/setup-python@v2 # Используем v2 для совместимости
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 PyQtWebEngine pyinstaller xlsxwriter
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --hidden-import=xlsxwriter --hidden-import=PyQt5.QtWebEngineWidgets --name FB_Group_Exporter main.py
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2 # Используем v2 для совместимости
      with:
        name: FB_Group_Exporter_Windows
        path: dist/FB_Group_Exporter.exe

  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Используем v2 для совместимости
    
    - name: Set up Python
      uses: actions/setup-python@v2 # Используем v2 для совместимости
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 PyQtWebEngine pyinstaller xlsxwriter
    
    - name: Build Mac executable
      run: |
        pyinstaller --onefile --windowed --hidden-import=xlsxwriter --hidden-import=PyQt5.QtWebEngineWidgets --name FB_Group_Exporter main.py
        mkdir -p dist/FB_Group_Exporter.app/Contents/MacOS
        mv dist/FB_Group_Exporter dist/FB_Group_Exporter.app/Contents/MacOS/FB_Group_Exporter
        chmod +x dist/FB_Group_Exporter.app/Contents/MacOS/FB_Group_Exporter
    
    - name: Upload Mac artifact
      uses: actions/upload-artifact@v2 # Используем v2 для совместимости
      with:
        name: FB_Group_Exporter_Mac
        path: dist/FB_Group_Exporter.app
