name: Build FB Group Exporter

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 PyQtWebEngine pyinstaller xlsxwriter
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name="FB_Group_Exporter" main.py
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: FB_Group_Exporter_Windows
        path: dist/FB_Group_Exporter.exe

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 PyQtWebEngine pyinstaller xlsxwriter
    
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --windowed --name="FB_Group_Exporter" main.py
    
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: FB_Group_Exporter_macOS
        path: dist/FB_Group_Exporter
