name: Build FB Group Exporter

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # SHA для v2
    
    - name: Set up Python
      uses: actions/setup-python@65d7f2d078d27f32f6f6967593aecd8d73086a47 # SHA для v2
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 PyQtWebEngine pyinstaller xlsxwriter
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --hidden-import=xlsxwriter --hidden-import=PyQt5.QtWebEngineWidgets --name FB_Group_Exporter main.py
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # SHA для v2
      with:
        name: FB_Group_Exporter_Windows
        path: dist/FB_Group_Exporter.exe

  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # SHA для v2
    
    - name: Set up Python
      uses: actions/setup-python@65d7f2d078d27f32f6f6967593aecd8d73086a47 # SHA для v2
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 PyQtWebEngine pyinstaller xlsxwriter
    
    - name: Build Mac executable
      run: |
        pyinstaller --onefile --windowed --hidden-import=xlsxwriter --hidden-import=PyQt5.QtWebEngineWidgets --name FB_Group_Exporter main.py
        mkdir -p dist/FB_Group_Exporter.app/Contents/MacOS
        mv dist/FB_Group_Exporter dist/FB_Group_Exporter.app/Contents/MacOS/FB_Group_Exporter
        chmod +x dist/FB_Group_Exporter.app/Contents/MacOS/FB_Group_Exporter
        codesign --force --deep --sign - dist/FB_Group_Exporter.app
    
    - name: Upload Mac artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # SHA для v2
      with:
        name: FB_Group_Exporter_Mac
        path: dist/FB_Group_Exporter.app
